# Generated by Django 2.1.5 on 2020-11-07 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_tag_name', models.CharField(max_length=30, verbose_name='自动分类')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('original', models.ImageField(upload_to='uploads')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, default=1, max_length=30)),
                ('width', models.IntegerField(default=1, verbose_name='图片宽度')),
                ('height', models.IntegerField(default=1, verbose_name='图片高度')),
                ('size', models.IntegerField(default=1, verbose_name='图片大小')),
                ('auto_tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pictures.Auto_Tag')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='Location_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_tag_name', models.CharField(max_length=30, verbose_name='地标分类')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='location_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pictures.Location_Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
